### ISSUE TITLE
EUGEN-T14-R047 doesn't trigger

### ISSUE THREAD

**Issue by klakegg** [OpenPEPPOL/peppol-bis#16]
Sample files:
https://github.com/difi/vefa-validator-conf/blob/updates-2016-05-23/rules/ehf-creditnote-2.0/test/T14-missing-invoice-reference.xml

Rule is listed in specification.

**Comment by SiwMeckelborg** [comment]
This issue is postponed, and a solution will be discussed further.

**Comment by phax** [comment]
PEPPOL-40
