### ISSUE TITLE
PEPPOL_CORE_R002 not triggered in T10-0044-PEPPOLCOREBreak.xml

### ISSUE THREAD

**Issue by klakegg** [OpenPEPPOL/peppol-bis#17]
PEPPOL_CORE_R002 is not triggered in T10-0044-PEPPOLCOREBreak.xml as it is ment to be. I don't know what in the file is ment to trigger this warning.

Please advise or fix test.

https://test-vefa.difi.no/validator/v/26964c2c-c9f2-4a06-839c-efcf85d7709b

**Comment by JesperLmySupply** [comment]
Hi Erlend,

I corrected the test file to test that CitySubdivisionName breaks the core:
<cac:PostalAddress>
         <cbc:StreetName>Storgata 3</cbc:StreetName>
         <cbc:CitySubdivisionName>Test</cbc:CitySubdivisionName>
         <cbc:CityName>SARPSBORG</cbc:CityName>
         <cbc:PostalZone>1701</cbc:PostalZone>

Venlig hilsen / Kind regards
Jesper Larsen
IT-Konsulent
mySupply ApS
Peter Løthsvej 2, 9440  Aabybro
Tlf.       +45 96961070
Tlf. Dir. +45 96962148
Fax:     +45 96961071
e-mail: Jesper.Larsen@mysupply.dk<mailto:Jesper.Larsen@mysupply.dk>

Fortrolighed
Denne e-mail og tilhørende bilag er fortrolige og må ikke videregives. Hvis du ikke er den rette modtager, anmodes du om at underrrette afsenderen herom samt om ikke at videregive indholdet til andre personer, anvende det til egne formål eller arkivere eller kopiere informationen til noget medium.
Confidentiality
This e-mail and any attachements are confidential and may also be privileged. If you are not the named recipient, please notify the sender immediately and do not disclouse the contents to another person, use it or any purpose, or store or copy the information in any medium.

Fra: Erlend Klakegg Bergheim [mailto:notifications@github.com]
Sendt: 25. april 2016 10:36
Til: OpenPEPPOL/peppol-bis
Emne: [OpenPEPPOL/peppol-bis] PEPPOL_CORE_R002 not triggered in T10-0044-PEPPOLCOREBreak.xml (#17)


PEPPOL_CORE_R002 is not triggered in T10-0044-PEPPOLCOREBreak.xml as it is ment to be. I don't know what in the file is ment to trigger this warning.

Please advise or fix test.

https://test-vefa.difi.no/validator/v/26964c2c-c9f2-4a06-839c-efcf85d7709b

**Comment by klakegg** [comment]
This is what I find when I use the generated XSLT on the test file using Saxon 9.7.0-4:

```xml
   <svrl:successful-report test="true()"
                           id="PEPPOL_CORE_R002"
                           flag="warning"
                           location="/*[local-name()='Invoice']/*[local-name()='AccountingCustomerParty']/*[local-name()='Party']/*[local-name()='PostalAddress']/*[local-name()='CitySubdivisionName']">
      <svrl:text>
	Element 'cbc:CitySubdivisionName' is marked as not used in the given context.</svrl:text>
   </svrl:successful-report>
```

I thought it should be of type "failed-assert", not "successful-report". Please adivse.

**Comment by phax** [comment]
PEPPOL-39
