### ISSUE TITLE
Unable to trace changes

### ISSUE THREAD

**Issue by klakegg** [OpenPEPPOL/peppol-bis#22]
Most commits in this repository for the new commit does not contain information about the changes performed or any releation to issues. This makes it very hard to track changes back to reported issues and even harder to verify issues are actually solved.

**Comment by phax** [comment]
Point taken - hopefully the commits now refer to the JIRA issues....

**Comment by klakegg** [comment]
I see a lot of recent changes without commit messages.

**Comment by phax** [comment]
Okay, please handle this bilaterally with Jesper :)
