### ISSUE TITLE
CL-T10-R001 check has no ID attribute in output

### ISSUE THREAD

**Issue by petersone** [OpenPEPPOL/peppol-bis#34]
During test of T10-0005-MultipleSchematronErrors.xml we get the error: problem: Expected error/warning CL-T10-R001 not found in schematron output

In the output we see:
```
<svrl:failed-assert test="( ( not(contains(normalize-space(.),' ')) and contains( ' 380 393 384 ',concat(' ',normalize-space(.),' ') ) ) )"
                       flag="fatal"
                       location="/*:Invoice[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'][1]/*:InvoiceTypeCode[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'][1]">
      <svrl:text>[CL-T10-R001]-An Invoice MUST be coded with the InvoiceTypeCode code list UNCL D1001 BII2 subset</svrl:text>
   </svrl:failed-assert>
```

The ID attribute is missing in output.

**Comment by klakegg** [comment]
CL-T10-R001 is triggered as expected.

**Comment by petersone** [comment]
Yes, CL-T10-R001 is triggered... but the ID attribute inside the svrl:failed-assert element is missing (see above).

Normal output (from all other) contains the ID attribute:
```
<svrl:failed-assert test="(cac:TaxCategory/cbc:Percent) or not(normalize-space(cac:TaxCategory/cbc:ID) = 'S')"
                       id="BII2-T10-R030"
                       flag="fatal"
                       location="/*:Invoice[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:Invoice-2'][1]/*:TaxTotal[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]/*:TaxSubtotal[namespace-uri()='urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'][1]">
      <svrl:text>[BII2-T10-R030]-The VAT category percentage MUST be provided if the VAT category code is standard.</svrl:text>
</svrl:failed-assert>
```

**Comment by klakegg** [comment]
This has been the case all the time, also when scripts were created initially more than a year ago.

**Comment by SiwMeckelborg** [comment]
I think Peter has a good point here, either all VAs should have an ID attribute, or not, but maybe an issue for next release, so we can discuss this, and also look at the multiple IDs in the core rules to ensure a solution that is the same for all artefacts, and are valid according to schematron rules.

**Comment by petersone** [comment]
Siw: Can you quickly add the missing ID attributes?

In the updated test engine I expect the ID attribute to exist (reg ex), when finding/matching thrown failed-assert in the schematron output.

**Comment by SiwMeckelborg** [comment]
This is not a quick fix, as it requires a review of all VAs to ensure they are all there.

**Comment by petersone** [comment]
Another approach could be adding the once we meet on our way...

**Comment by petersone** [comment]
Added missing ID attributes to all OPENPEPPOLCodesTxx-UBL.sch files.
