### ISSUE TITLE
Unable to run ant script

### ISSUE THREAD

**Issue by klakegg** [OpenPEPPOL/peppol-bis#35]
When I try to run the ant script in a Linux environment, I get this error:

```
test:

parseTestFilePath:

schematronValidateFile:
     [echo] ##teamcity[testSuiteStarted name='Ts/' flowId='12321']
     [echo] ##teamcity[testStarted name='T01-0001-valid.xml' flowId='12321']
     [java] Stylesheet file ../target/XSLT/BIIRULES-UBL-Ts/.xsl does not exist

BUILD FAILED
peppol-bis/script/build.xml:152: The following error occurred while executing this line:
peppol-bis/script/build.xml:446: Java returned: 2
```

It should be possible for others than the TeamCity server in Denmark to run this script during development.

**Comment by petersone** [comment]
I have no problem executing "ant build-all" in my local CygWin.
```
test:

parseTestFilePath:

schematronValidateFile:
     [echo] ##teamcity[testSuiteStarted name='T01' flowId='12321']
     [echo] ##teamcity[testStarted name='T01-0001-valid.xml' flowId='12321']

executeTest:
     [echo] ##teamcity[testFinished name='T01-0001-valid.xml' flowId='12321']
     [echo] ##teamcity[testSuiteFinished name='T01' flowId='12321']

parseTestFilePath:

schematronValidateFile:
     [echo] ##teamcity[testSuiteStarted name='T01' flowId='12321']
     [echo] ##teamcity[testStarted name='T01-0002-valid Allowance without Tax.xml' flowId='12321']
...
executeTest:
     [echo] ##teamcity[testFailed name='T76-1500-invalid.xml' message='Expected error/warning OP-T76-R007 not found in schematron output' flowId='12321']
     [echo] ##teamcity[testFinished name='T76-1500-invalid.xml' flowId='12321']
     [echo] ##teamcity[testSuiteFinished name='T76' flowId='12321']
     [copy] Copying 1 file to D:\Projekter\peppol-bis-2.0\trunk\target
   [delete] Deleting: D:\Projekter\peppol-bis-2.0\trunk\target\test-overview-inner.html

makeZip:
      [zip] Building zip: D:\Projekter\peppol-bis-2.0\trunk\target\BIS2.0-VA-V3.3.0_RC1.20160928_090419.zip

build-all:

BUILD SUCCESSFUL
Total time: 7 minutes 40 seconds
```

**Comment by klakegg** [comment]
https://travis-ci.org/OpenPEPPOL/peppol-bis/jobs/163321578

**Comment by petersone** [comment]
Your output is:
schematronValidateFile:
     [echo] ##teamcity[testSuiteStarted name='Tpe' flowId='12321']

My output is:
schematronValidateFile:
     [echo] ##teamcity[testSuiteStarted name='T01' flowId='12321']

This indicates, that you have some tests named .../Tests/Tpe*
That's why target/XSLT/BIIRULES-UBL-Tpe.xsl does not exist.

**Comment by klakegg** [comment]
The output on Travis is based on an unchanged checkout of this project, just like in my environment. They produce slightly different results, but basically it does not work.

**Comment by petersone** [comment]
I can say "the same":
The output on TeamCity + local DOS + local CygWin is based on an unchanged checkout of this project - and here it works!

**Comment by klakegg** [comment]
Is it a requirement to run TeamCity + local DOS + local CygWin to expect the script to work?

**Comment by petersone** [comment]
No... it works using apache-ant-1.7.1 in all 3 cases (individually).

**Comment by klakegg** [comment]
So Apache Ant 1.9.3 on Linux is not supported?

**Comment by petersone** [comment]
As far as I know - yes it is.
I'm not running a "pure" Linux (company policy), but use CygWin installation. My apache-ant-1.7.1/bin/ant is a sh file... so yes: I think it's fully supported.

**Comment by klakegg** [comment]
No, it doesn't.
https://travis-ci.org/OpenPEPPOL/peppol-bis/jobs/163642721

**Comment by petersone** [comment]
Erlend... come on... Ant ARE running on your server:
```
$ sh .travis.$PERFORM.sh

Buildfile: /home/travis/build/OpenPEPPOL/peppol-bis/script/build.xml

clean:

setBuildNumber.normal:

init:

     [echo] ##teamcity[buildNumber '3.3.0_RC1.20160929_081855']

    [mkdir] Created dir: /home/travis/build/OpenPEPPOL/peppol-bis/target/XSLT

compile:

dir.check:

compileDocumentType:

compileSchFile:
...
```

I found and corrected an build script error, so that Linux path separators (/) are recognized (and not only Windows (\)).

**Comment by klakegg** [comment]
The tests still doesn't run.

**Comment by petersone** [comment]
All green lights for ANT - right???
https://travis-ci.org/OpenPEPPOL/peppol-bis/builds/163727796

**Comment by klakegg** [comment]
Good, thank you.

**Comment by petersone** [comment]
![image](https://cloud.githubusercontent.com/assets/12168546/18957936/392e727e-8661-11e6-9620-1cf4cf41fa33.png)
