### ISSUE TITLE
BII2-T10-R049 cannot deal with multiple cac:TaxTotal/cac:TaxSubtotal with cac:TaxCategory/cbc:ID = "AE"

### ISSUE THREAD

**Issue by KevinVG** [OpenPEPPOL/peppol-bis#37]
When an Invoice has multuple cac:TaxTotal/cac:TaxSubTotal with the ID = "AE", the validator crashes with the error: "A sequence of more than one item is not allowed as the value in 'cast as' expression."

This is the result of the "decimal()" function in the rule description which can only accept one value. The rule:
`<param name="BII2-T10-R049" value="(xs:decimal(cac:TaxTotal/cac:TaxSubtotal[cac:TaxCategory/cbc:ID = 'AE']/cbc:TaxableAmount) = xs:decimal(cac:LegalMonetaryTotal/cbc:TaxExclusiveAmount)) or  not(cac:TaxTotal[cac:TaxSubtotal/cac:TaxCategory/cbc:ID = 'AE'])"/>`

When multiple "AE" fields are used, there is more than 1 value and the crash occurs. Either the number of 'AE' taxsubtotals should be limited or the rule should account for more than 1 value.

**Comment by phax** [comment]
We have a different progress tracker where this is taken care of :)

**Comment by phax** [comment]
Suggested resolution:

The combination of CategoryCode+Rate must be unique. However- VAT exempts (category code E) may have different reason codes but the same rate (0).

**Comment by oriol** [comment]
Final decision to accomodate the Belgian need and allow multiple taxcategory with AE and E with rate 0. Fixed in 3.4.0
