### ISSUE TITLE
3.3.0: A sequence of more than one item is not allowed as the value in 'cast as' expression

### ISSUE THREAD

**Issue by phax** [OpenPEPPOL/peppol-bis#39]
File: `3.3.0/SCH/peppolbis-trdm010-2.0-invoice/Schematron/BII RULES/BIIRULES-UBL-T10.sch`

Failed to evaluate XPath expression to a boolean: `(xs:decimal(cac:TaxTotal/cac:TaxSubtotal[cac:TaxCategory/cbc:ID = 'AE']/cbc:TaxAmount) = 0) or  not(cac:TaxTotal[cac:TaxSubtotal/cac:TaxCategory/cbc:ID = 'AE'])`

Error message: `A sequence of more than one item is not allowed as the value in 'cast as' expression (<cbc:TaxAmount/>, <cbc:TaxAmount/>) `

XML fragment:
```xml
	<cac:TaxTotal>
		<cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
		<cac:TaxSubtotal>
			<cbc:TaxableAmount currencyID="EUR">400.00</cbc:TaxableAmount>
			<cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
			<cac:TaxCategory>
				<cbc:ID schemeID="UNCL5305">AE</cbc:ID>
				<cbc:Percent>0.00</cbc:Percent>
				<cbc:TaxExemptionReasonCode>BF01</cbc:TaxExemptionReasonCode>
				<cbc:TaxExemptionReason>Levering van goederen niet onderworpen aan Belgische BTW. Art. 14. § 1 van het WBTW</cbc:TaxExemptionReason>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:TaxCategory>
		</cac:TaxSubtotal>
		<cac:TaxSubtotal>
			<cbc:TaxableAmount currencyID="EUR">300.00</cbc:TaxableAmount>
			<cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
			<cac:TaxCategory>
				<cbc:ID schemeID="UNCL5305">AE</cbc:ID>
				<cbc:Percent>0.00</cbc:Percent>
				<cbc:TaxExemptionReasonCode>BF01</cbc:TaxExemptionReasonCode>
				<cbc:TaxExemptionReason>Levering van goederen niet onderworpen aan Belgische BTW. Art. 14. § 1 van het WBTW</cbc:TaxExemptionReason>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:TaxCategory>
		</cac:TaxSubtotal>
	</cac:TaxTotal>
```

**Comment by SiwMeckelborg** [comment]
This issue is the same as issue #37

**Comment by phax** [comment]
You officially decided to move to XPath 2 right?
So why not using `fn:round-half-to-even` (https://www.w3.org/TR/xpath-functions/#func-round-half-to-even) or `fn:round` (https://www.w3.org/TR/xpath-functions/#func-round).

We didn't use them originally, since only XPath 1 was allowed....

**Comment by SiwMeckelborg** [comment]
The reason for this is issues with floating point numbers. A number like 123.345 does not have an exact equal floating point number, and the result is that some variants of decimals rounds up and others down.
