### ISSUE TITLE
DespatchAdvice check 'BII2-T16-R018' is not implemented correctly

### ISSUE THREAD

**Issue by monze** [OpenPEPPOL/peppol-bis#43]
Hey

I don't thing the implementation of the 'BII2-T16-R018' check is correct.
It basic validate, that if a `cac:StandardItemIdentification` element exist, at least one of theses elements must contain a `cac:Item/@schemeID` attribute. It does **not** validate that all `cac:StandardItemIdentification` elements must contain a `cac:Item/@schemeID` attribute.

So if a Despatch document have 5 DespatchLine, where each line having a `cac:Item/cac:StandardItemIdentification/cac:Item` element, it is enough to have the `schemeID` attribute in the first `DespatchLine/cac:Item/cac:StandardItemIdentification/cac:Item` element.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by phax** [comment]
Hi Jacob, your issue will be handled in the OpenPEPPOL internal JIRA - we will keep you posted here. Thx
