### ISSUE TITLE
The rule BII2-T01-R009 is incomplete

### ISSUE THREAD

**Issue by roberto-cisternino** [OpenPEPPOL/peppol-bis#48]
The actual rule just checks the existance of the Document Currency Code, but it should check the consistent use of a unique currency code within the document.

(cbc:DocumentCurrencyCode)

**Comment by roberto-cisternino** [comment]
This bug can be resolved with the following rule expression:

cbc:DocumentCurrencyCode[normalize-space()] and count(//@currencyID)=count(//*[@currencyID=/*/cbc:DocumentCurrencyCode])

**Comment by SiwMeckelborg** [comment]
This is solved in the BIS 3 Upgrade project, you can check the rule here:
http://test-docs.peppol.eu/poacc/upgrade-3/rules/PEPPOL-T01-R003/

There will not be any updates in the current BIS 2 validations unless severe errors are found, hence I close this issue. If you find this to be wrong, please raise your issue as an RfC to openPEPPOL PoACC here: https://openpeppol.atlassian.net/servicedesk/customer/portal/1
