### ISSUE TITLE
The rule OP-T01-R008 should be applied to the cac:Item/cac:ClassifiedTaxCategory

### ISSUE THREAD

**Issue by roberto-cisternino** [OpenPEPPOL/peppol-bis#49]
The rule OP-T01-R008 should be applied to the cac:Item/cac:ClassifiedTaxCategory context too.
The rule is technically correct but context is insufficient.

**Comment by roberto-cisternino** [comment]
The fix is to correct the rule context as follows:
//cac:TaxCategory/cbc:ID | //cac:ClassifiedTaxCategory/cbc:ID

**Comment by SiwMeckelborg** [comment]
In the PEPPOL BIS upgrade project, the codelist 5305 (Subset) is mandated for both TaxCategory and ClassifiedTaxCategory:
http://test-docs.peppol.eu/poacc/upgrade-3/syntax/Order/cac-AllowanceCharge/cac-TaxCategory/cbc-ID/
http://test-docs.peppol.eu/poacc/upgrade-3/syntax/Order/cac-OrderLine/cac-LineItem/cac-Item/cac-ClassifiedTaxCategory/cbc-ID/

There will not be any updates in the current BIS 2 validations unless severe errors are found, hence I close this issue. If you find this to be wrong, please raise your issue as an RfC to openPEPPOL PoACC here: https://openpeppol.atlassian.net/servicedesk/customer/portal/1
