### ISSUE TITLE
BII2-T01-R006 do not check the presence of the order ID value

### ISSUE THREAD

**Issue by roberto-cisternino** [OpenPEPPOL/peppol-bis#50]
The following expression is more precise as the presence of a non-empty value is checked:

cbc:ID[normalize-space()]

**Comment by SiwMeckelborg** [comment]
In the PEPPOL BIS upgrade project, this is solved by ensuring no empty elements are present: http://test-docs.peppol.eu/poacc/upgrade-3/rules/PEPPOL-COMMON-R001/
http://test-docs.peppol.eu/poacc/upgrade-3/rules/PEPPOL-COMMON-R002/

There will not be any updates in the current BIS 2 validations unless severe errors are found, hence I close this issue. If you find this to be wrong, please raise your issue as an RfC to openPEPPOL PoACC here: https://openpeppol.atlassian.net/servicedesk/customer/portal/1
