### ISSUE TITLE
Stylesheet for peppol-bis-invoice-3: uri is missing for xmlns:u

### ISSUE THREAD

**Issue by agendec-com** [OpenPEPPOL/peppol-bis#52]
Regarding the stylesheet for peppol-bis-invoice-3:
The uri is missing for xmlns:u.

**Comment by SiwMeckelborg** [comment]
When creating functions inside an xslt (using xslt2.0 or 3.0), these functions must be in a non-default namespace, and the namespace can more or less be whatever, as long as it is not the default namespace. So to my knowledge, the xmlns:u="utils" is just a "dummy" value to use when creating the functions, like this:

  <xsl:function name="u:label">
        <xsl:param name="part"/>
        <xsl:param name="value"/>
...
</xsl:function>

Hope this helps, if not, let me know.

**Comment by phax** [comment]
Saxon 9.8/9.9 HE wont let you compile it, if the "u" prefix is not bound

**Comment by SiwMeckelborg** [comment]
It is bound
xmlns:u="utils"

**Comment by BjornJonssonVisma** [comment]
I get the same problem when using XslCompiledTransform in C# "Cannot find a script or an extension object associated with namespace 'utils'."

**Comment by SiwMeckelborg** [comment]
I am sorry for what might be A stupid question, but I have no knowledge of the XslCompiledTransform, does it support Xslt 2.0?

**Comment by BjornJonssonVisma** [comment]
You are correct,  XslCompiledTransform does not support xslt 2.0 (I assumed that it did),

**Comment by agendec-com** [comment]
Thank you for your reply Siw.
I am using .Net framework (XslCompiledTransform) and the reason is like BjornJonssonVisma points out that it doesn't support xslt 2.0/3.0.
I took it for granted that Microsoft had implemented support for that.
There's a feature request for this at MS dev community which I now have added a vote on:
https://developercommunity.visualstudio.com/content/idea/351285/implement-xslt-30-for-net.html.
